[directory]
truncate_to_repo = false

[memory_usage]
disabled = false
format = '[\[${ram}\]]($style) '
threshold = -1
style = "bold dimmed purple"

[shlvl]
disabled = false
threshold = 3 # already at 2 in tmux

[git_status]
format = '([$staged$modified$untracked$conflicted$stashed$deleted$renamed$ahead_behind]($style) )'
staged = '[\($count\)](green bold)'
modified = '[\($count\)](red bold)'
untracked = '[\($count\)](yellow bold)'
conflicted = '[\(conflicts: $count\)](green bold)'
stashed = '[\(stash\)](yellow bold)'
deleted = '[ ✘$count ](red bold)'
renamed = '[ »$count ](yellow bold)'
ahead = "[⇡${count}](white bold)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](white bold)"
behind = "[⇣${count}](white bold)"
style = "bold purple"

[ruby]
format = '[(\(ruby $version\) )](white dimmed bold)'

[python]
format = '[(\(python $version\) )](white dimmed bold)'
