Metrics/LineLength:
  Max: 120

MethodLength:
  Max: 50

BlockLength:
  Max: 100

Metrics/AbcSize:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false
