version: '3'
services:
  devenv:
    image: "${IMAGE}:${TAG}"
    volumes:
      - ${PWD}:${PWD}
      - rvm:/root/.rvm
      - ${DEVENV_HOST_SSH_AUTH_SOCK}:${DEVENV_CONTAINER_SSH_AUTH_SOCK}
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      - SSH_AUTH_SOCK=${DEVENV_CONTAINER_SSH_AUTH_SOCK}
    working_dir: ${PWD}
volumes:
  rvm:
