version: '3'
services:
  devenv:
    image: "${IMAGE}:${TAG}"
    volumes:
      - ${PWD}:${PWD}
      - rvm:/root/.rvm
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    working_dir: ${PWD}
volumes:
  rvm:
