#!/bin/bash

set -eu -o pipefail

export IMAGE="hongtron/dev-env"
export TAG="latest"

usage() {
  cat <<EOF
devenv [-i <image>] [-t <tag>] [COMMAND]
Options
  -i, --image     Specify docker image; defaults to "hongtron/dev-env"
  -t, --tag       Specify docker image tag; defaults to "latest"
EOF
}


if [[ "$PWD" == "$HOME" ]]; then
  echo "Do not run devenv from home directory, as the container's dotfiles will be mounted over."
  exit 1
fi


while [[ $# > 0 && $1 == -* ]]; do
  case $1 in
    -i|--image)
      shift
      export IMAGE=$1
      ;;
    -t|--tag)
      shift
      export TAG=$1
      ;;
    -h|--help)
      usage
      exit
      ;;
  esac

  shift
done


# https://github.com/docker/for-mac/issues/410
unamestr=`uname`
if [[ "$unamestr" == 'Darwin' ]]; then
  export DEVENV_HOST_SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock"
  export DEVENV_CONTAINER_SSH_AUTH_SOCK="/run/host-services/ssh-auth.sock"
else
  export DEVENV_HOST_SSH_AUTH_SOCK="${SSH_AUTH_SOCK}"
  export DEVENV_CONTAINER_SSH_AUTH_SOCK="/ssh-agent"
fi

if [[ $* ]]; then
  docker-compose -f /usr/local/etc/devenv/docker-compose.yml run --rm devenv /bin/bash -i -c "$*"
else
  docker-compose -f /usr/local/etc/devenv/docker-compose.yml run --rm devenv
fi
